### ISSUE TITLE
能否更改使用指令

### ISSUE THREAD

**Issue by TogetsuDo** [MerCuJerry/nonebot-plugin-blocker#1]
比如某某关机这样

**Comment by MerCuJerry** [comment]
> 比如某某关机这样

可以的 我做成命令别名的方式吧 从配置项里直接配置

虽然说我这么写也不是命令别名了（

**Comment by MerCuJerry** [comment]
> 比如某某关机这样

传了一个版本 你根据新的文档试试看好不好使

**Comment by TogetsuDo** [comment]
> > 比如某某关机这样
> 
> 
> 
> 传了一个版本 你根据新的文档试试看好不好使

解决了，感谢
